Issue 1235 dataset
ansys/pyaedt pull request #1280
Opened 2022-06-13 15:51 UTC by zebanaqviWAT

2022-06-14 10:28 UTC, maxcapodi78 approved these changes
LGTM

2022-06-14 10:28 UTC, maxcapodi78 commented on pyaedt/application/Design.py
> +    def import_dataset3d(self, filename, encoding="utf-8-sig", dsname=None):
To keep back compatibility better to add the new args at the end of the method

```suggestion
    def import_dataset3d(self, filename, dsname=None, encoding="utf-8-sig"):
```

2022-06-14 10:28 UTC, maxcapodi78 requested changes
apart a small suggestion it looks good to me

2022-06-14 10:30 UTC, maxcapodi78 requested changes
2 changes needed

2022-06-14 10:30 UTC, maxcapodi78 commented on _unittest/test_01_Design.py
> +        filename = os.path.join(local_path, "example_models", "Dataset_3D.xlsx")
To test the excel import you need pandas on the build machine. add it to requirements_test.txt

2022-06-14 13:18 UTC, Samuelopez-ansys approved these changes
LGTM

2022-06-14 14:40 UTC, Samuelopez-ansys approved these changes

2022-06-15 07:17 UTC, MaxJPRey commented on pyaedt/application/Design.py
> +            self.logger.warning("Warning: You need pandas installed for reading excel files")
```suggestion
            self.logger.warning("You need pandas library installed for reading excel files")
```

2022-06-15 07:19 UTC, MaxJPRey commented on pyaedt/application/Design.py
> +                    "Pandas is not installed. Either install pandas or save the file as .csv or .tab. " "Exiting."
What is the `" "` for before `Exiting` in the log message?

2022-06-15 07:21 UTC, MaxJPRey commented on pyaedt/application/Design.py
> +            df = pd.read_excel(filename)
If possible, could you use a more specific variable name?

2022-06-15 07:26 UTC, MaxJPRey commented on pyaedt/application/Design.py
> +            my_file.close()
@zebanaqviWAT You don't need to close the file hear as you are using a `with open` statement that will take care of closing the file after reading its content (here with the `readlines()` method).
```suggestion
```

2022-06-15 14:53 UTC, maxcapodi78 approved these changes
lgtm

2022-06-15 15:08 UTC, merged