Edb create padstack definition hole range buf fix
ansys/pyaedt pull request #3276
Opened 2023-07-14 14:38 UTC by svandenb-dev

There are different hole range for padstack definitions. Not all combinations were implemented.

2023-07-14 18:49 UTC, ring630 commented
@svandenb-dev, please add a hole_range property in EDBPadProperties class

2023-07-15 15:45 UTC, MaxJPRey approved these changes
LGTM.

2023-07-18 07:37 UTC, maxcapodi78 requested changes

2023-07-19 08:31 UTC, svandenb-dev commented on pyaedt/edb_core/edb_data/padstacks_data.py
> +    def hole_range(self):
Done

2023-07-25 15:39 UTC, merged