implement object CS
ansys/pyaedt pull request #3557
Opened 2023-09-13 15:40 UTC by gmalinve

2023-09-13 16:57 UTC, Alberto-DM requested changes
Hi gmalinve, we need to have a call about this PR :)

2023-09-14 13:23 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        Id of the entity object where the Object Coordinate System is anchored.
```suggestion
        The default is ``None``.
    entity_id : int
        ID of the entity object where the object coordinate system is anchored.
```
Avoid unnecessary capitalization--reserve for proper nouns or matching tagged code entities. Don't forget to add a description for name.

2023-09-14 13:23 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        """Reference coordinate system getter and setter.
```suggestion
        """Reference coordinate system.
```
According to Alex K, we didn't need the getter and setter indication.

2023-09-14 13:25 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        """Internally get the part name of the object where the coordinate system lays"""
```suggestion
        """Internal part name of the object where the coordinate system lays."""
```
Properties should be described as nouns and not with a verb like "get". I'm not sure if "Internal" should be deleted from this description.

2023-09-14 13:26 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        """Internal named array for attributes of the object coordinate system."""
```suggestion
        """Internally named array for attributes of the object coordinate system."""
```

2023-09-14 13:26 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            Type of Object Coordinate System.
```suggestion
            Type of the object coordinate system.
```

2023-09-14 13:29 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            It can be the Id of the object or an object of type VertexPrimitive, EdgePrimitive, FacePrimitive.
```suggestion
            Entity where the object coordinate system is anchored.
            You can specify the ID of the object or an object of type VertexPrimitive, EdgePrimitive,
            or FacePrimitive.
```
Will the types be links or will they need to be tagged as code?

2023-09-14 13:31 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            x_axis_entity has to be provided only if cs_type is set to ``Both``.
```suggestion
            Entity that the x axis of the object coordinate system points to.
            You can specify the ID of the object or an object of type VertexPrimitive,
            EdgePrimitive, or FacePrimitive. A value for this parameter must be
            provided only if the ``cs_type`` is set to ``"Both"``.
```

2023-09-14 13:38 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        #     This option can be provided if the coordinate system type is either ``Rotated`` or ``Both``.
```suggestion
        #     This option can be provided if the coordinate system type is either ``"Rotated"`` or ``"Both"``.
```
Assuming the type is a string, the value need to have double back ticks and quotation marks.

2023-09-14 13:41 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +                    raise ValueError("origin must identify either Face or Edge or Vertex.")
```suggestion
                    raise ValueError("Origin must identify either `Face`, 'Edge', or 'Vertex'.")
```
Message strings should be complete sentences. If you don't want to tag the options as possible values, use lowercase letters.

2023-09-14 13:41 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +                        raise ValueError("x axis must identify either Face or Edge or Vertex.")
Same comment here for either tagging as possible values or lowercase to format as general text.

2023-09-14 13:42 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +                    raise ValueError("origin must identify either Face or Edge or Vertex.")
Same edits are needed here as indicated earlier.

2023-09-14 13:42 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            raise ValueError("Update property name failed.")
```suggestion
            raise ValueError("Update of property name failed.")
```

2023-09-14 13:43 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            raise ValueError("Update property move to end failed.")
```suggestion
            raise ValueError("Update of property move to end failed.")
```

2023-09-14 13:43 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            raise ValueError("Update property reverse x axis failed.")
```suggestion
            raise ValueError("Update of property reverse x axis failed.")
```

2023-09-14 13:43 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            raise ValueError("Update y axis properties failed.")
```suggestion
            raise ValueError("Update of y axis properties failed.")
```

2023-09-14 13:43 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +            raise ValueError("Update property reverse y axis failed.")
```suggestion
            raise ValueError("Update of property reverse y axis failed.")
```

2023-09-14 13:44 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
>      """Manages Lists data and execution.
```suggestion
    """Manages list data and execution.
```

2023-09-14 13:45 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        cs_type : str
Edit these parameter descriptions as indicated earlier.

2023-09-18 19:17 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        The default is ``None``.
Name of what? A description is needed for the ``name`` parameter.

2023-09-18 19:24 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +             - list in which case it refers to the point coordinate system ``[x, y, z]`` that the y axis points to.
```suggestion
        obj : str, :class:`pyaedt.modeler.cad.object3d.Object3d`
            Object to attach the object coordinate system to.
        origin : int, VertexPrimitive, EdgePrimitive, FacePrimitive, list
            Origin where the object coordinate system is anchored.
            The value can be:

             - An integer, in which case it refers to the entity ID.
             - A VertexPrimitive, EdgePrimitive, or FacePrimitive object, in which case it refers to the entity type.
             - A list, in which case it refers to the origin coordinate system ``[x, y, z]``.
        x_axis : int, VertexPrimitive, EdgePrimitive, FacePrimitive, list
            Entity that the x axis of the object coordinate system points to.
            The value can be:

             - An integer, in which case it refers to the entity IDd.
             - A VertexPrimitive, EdgePrimitive, or FacePrimitive object, in which case it refers to the entity type.
             - A list, in which case it refers to the point coordinate system ``[x, y, z]`` that the x axis points to.
        y_axis : int, VertexPrimitive, EdgePrimitive, FacePrimitive, list
            Entity that the y axis of the object coordinate system points to.
            The value can be:

             - An integer, in which case it refers to the entity ID.
             - A VertexPrimitive, EdgePrimitive, FacePrimitive object, in which case it refers to the entity type.
             - A list, in which case it refers to the point coordinate system ``[x, y, z]`` that the y axis points to.

```

2023-09-19 09:12 UTC, Alberto-DM approved these changes

2023-09-19 09:12 UTC, Alberto-DM approved these changes
LGTM. Great job!

2023-09-19 15:46 UTC, PipKat commented on pyaedt/modeler/cad/Modeler.py
> +        Clean all coordinate systems of the design.
```suggestion
        Clean all coordinate systems in the design.
```
Should "Clean" be changed to "Delete" or "Clear"?

2023-09-20 08:14 UTC, merged

2023-09-20 08:15 UTC, MaxJPRey commented on pyaedt/modeler/cad/Modeler.py
> +             - An integer, in which case it refers to the entity IDd.
```suggestion
             - An integer, in which case it refers to the entity ID.
```