EDB - Load amat material file from Aedt
ansys/pyaedt pull request #3713
Opened 2023-10-05 15:10 UTC by svandenb-dev

Loading amat material in EDB

2023-10-05 16:12 UTC, ring630 requested changes

2023-10-05 16:12 UTC, ring630 commented on pyaedt/edb_core/materials.py
> +    def load_material_from_aedt(self):
@svandenb-dev, I suggest to rename the method to 

`def load_sys_library(self):`

2023-10-05 16:12 UTC, ring630 commented on pyaedt/edb_core/materials.py
> +        material_dict = self._read_materials()
@svandenb-dev please add docstring.

2023-10-06 12:24 UTC, maxcapodi78 approved these changes

2023-10-06 16:34 UTC, PipKat commented on pyaedt/edb_core/materials.py
> +        bool
```suggestion
        bool
            "True`` when successful, ``False`` when failed.
```

2023-10-06 19:48 UTC, merged