install motor toolkit
ansys/pyaedt pull request #3724
Opened 2023-10-09 08:26 UTC by gmalinve

2024-03-01 16:20 UTC, SMoraisAnsys requested changes

2024-03-01 16:20 UTC, SMoraisAnsys commented on pyaedt/misc/install_extra_toolkits.py
> +    },
```suggestion
    "MagnetSegmentationWizard": {
        "pip": "git+https://github.com/ansys/magnet-segmentation-toolkit.git",
        "image": "pyansys.png",
        "toolkit_script": "src/ansys/aedt/toolkits/magnet_segmentation/run_toolkit.py",
        "installation_path": "Maxwell3d",
        "package_name": "magnet-segmentation-toolkit",
    },
```

2024-03-02 05:36 UTC, MaxJPRey approved these changes
LGTM.

2024-03-02 17:28 UTC, SMoraisAnsys approved these changes
LGTM

2024-03-08 09:51 UTC, Samuelopez-ansys approved these changes

2024-03-08 09:52 UTC, merged