create port enhancement
ansys/pyaedt pull request #3813
Opened 2023-10-27 13:16 UTC by ring630

```
        U7 = edbapp.components["U7"]
        U7.pins["G7"].create_port()
        port = U7.pins["F7"].create_port(reference=U7.pins["E7"])
        port.is_circuit_port = True
        _, pin_group = edbapp.siwave.create_pin_group_on_net(
            reference_designator="U7", net_name="GND", group_name="U7_GND"
                                              )
        U7.pins["F7"].create_port(reference=pin_group)
```

2023-10-27 13:31 UTC, ring630 commented
@SMoraisAnsys this is edb related.

2023-10-27 14:18 UTC, PipKat commented on pyaedt/edb.py
> +        terminal : class:`pyaedt.edb_core.edb_data.terminals.EdgeTerminal`,
Please add brief descriptions for the two terminal parameters.

2023-10-27 14:20 UTC, PipKat commented on pyaedt/edb_core/edb_data/padstacks_data.py
> +            Name of the port.
```suggestion
            Name of the port. The default is ``None``, in which case a name is automatically assigned.
```
The description of the behavior that occurs when ``None`` is used is a guess. Please revise if it is wrong.

2023-10-27 14:20 UTC, PipKat commented on pyaedt/edb_core/edb_data/padstacks_data.py
> +                    class:`pyaedt.edb_core.edb_data.sources.PinGroup`,
Add a brief description for "reference" parameter.

2023-10-27 14:20 UTC, PipKat commented on pyaedt/edb_core/edb_data/padstacks_data.py
> +                    class:`pyaedt.edb_core.edb_data.sources.PinGroup`,
```suggestion
                    class:`pyaedt.edb_core.edb_data.sources.PinGroup`, optional
```

2023-10-27 14:22 UTC, PipKat commented on pyaedt/edb_core/edb_data/padstacks_data.py
>          """Return Edb padstack object."""
```suggestion
        """EDB padstack object."""
```

2023-10-27 14:24 UTC, PipKat commented on pyaedt/edb_core/edb_data/sources.py
> +        """Get terminal."""
```suggestion
        """Terminal."""
```
Properties are described as nouns.

2023-10-27 14:24 UTC, PipKat commented on pyaedt/edb_core/edb_data/sources.py
> +            Name of the terminal.
```suggestion
            Name of the terminal. The default is ``None``, in which case a name is
            automatically assigned.
```

2023-10-27 14:25 UTC, PipKat commented on pyaedt/edb_core/edb_data/terminals.py
> +            Whether it is a reference terminal.
```suggestion
            Whether it is a reference terminal. The default is ``False``.
```

2023-10-31 13:11 UTC, svandenb-dev requested changes

2023-10-31 13:11 UTC, svandenb-dev commented on pyaedt/edb_core/edb_data/sources.py
> +            term = term.create(name, self.net_name, self.name)
I don't quite understand. the method _create_terminal creates actually a PingroupTerminal whichius different. I found it confusing

2023-10-31 13:11 UTC, svandenb-dev commented on pyaedt/edb_core/edb_data/sources.py
> +        term = PinGroupTerminal(self._pedb, self._edb_pin_group.GetPinGroupTerminal())
Here property terminal is returning a PingroupTerminal ?

2023-10-31 13:30 UTC, svandenb-dev commented on pyaedt/edb_core/edb_data/sources.py
> +            term = term.create(name, self.net_name, self.name)
ok with this one LGTM

2023-10-31 13:30 UTC, svandenb-dev approved these changes

2023-10-31 13:42 UTC, merged