Add `get_sweeps` and `delete_sweep` to `SetupHFSS`
ansys/pyaedt pull request #4072
Opened 2024-01-15 09:29 UTC by atlanswer

Add two methods `get_sweeps` and `delete_sweep` to the `SetupHFSS` class according to the scripting guide.

Related tests are included.

2024-01-15 10:30 UTC, MaxJPRey commented on pyaedt/modules/SolveSetup.py
> +            Array of sweep names.
```suggestion
            Tupple of sweep names.
```

2024-01-15 10:30 UTC, MaxJPRey commented on pyaedt/modules/SolveSetup.py
> +        >>> hfss = Hfss()
```suggestion
        >>> import pyaedt
        >>> hfss = pyaedt.Hfss()
```

2024-01-15 15:39 UTC, Samuelopez-ansys approved these changes

2024-01-15 15:39 UTC, Samuelopez-ansys commented on pyaedt/modules/SolveSetup.py
> +    def get_sweeps(self):
```suggestion
    def get_sweep_names(self):
```
I would change the name to have naming consistency with other PyAEDT methods

2024-01-15 15:41 UTC, Samuelopez-ansys requested changes

2024-01-15 15:41 UTC, Samuelopez-ansys commented on pyaedt/modules/SolveSetup.py
> +        >>> sweeps = setup.get_sweeps()
```suggestion
        >>> sweeps = setup.get_sweep_names()
```

2024-01-15 15:41 UTC, Samuelopez-ansys commented on pyaedt/modules/SolveSetup.py
> +        if sweepname in self.get_sweeps():
```suggestion
        if sweepname in self.get_sweep_names():
```

2024-01-15 15:41 UTC, Samuelopez-ansys commented on _unittest/test_11_Setup.py
> +        sweeps = setup1.get_sweeps()
```suggestion
        sweeps = setup1.get_sweep_names()
```

2024-01-15 15:42 UTC, Samuelopez-ansys commented
@atlanswer Please check my comments. Did you check if somewhere else the sweep is still available after you delete it? I will review it later on.

2024-01-15 16:07 UTC, atlanswer commented
@Samuelopez-ansys Thanks. I think sweeps are stored in `SetupHFSS.sweeps` and in AEDT. Both are deleted here.

2024-01-16 07:42 UTC, Samuelopez-ansys approved these changes
Great enhacement!

2024-01-16 08:00 UTC, merged