Polygon operations added
ansys/pyaedt pull request #4127
Opened 2024-01-24 14:55 UTC by svandenb-dev

Added:
polygon.move method
polygon.rotate method
polygon.scale method
polygon.move_layer method

2024-01-24 15:34 UTC, ring630 approved these changes
LGTM

2024-01-25 10:43 UTC, SMoraisAnsys requested changes
Great job here, just a missing docstring description.
Btw, can't the scaling factor of `scale` be an integer ?

2024-01-25 10:43 UTC, SMoraisAnsys commented on pyaedt/edb_core/edb_data/primitives_data.py
> +        """
```suggestion
        """Move polygon along a vector.
```

2024-01-25 10:43 UTC, SMoraisAnsys commented on pyaedt/edb_core/edb_data/primitives_data.py
> +                    return self.api_object.SetPolygonData(polygon_data)
```suggestion
        if vector and isinstance(vector, list) and len(vector) == 2:
            _vector = self._edb.Geometry.PointData(
                self._edb.Utility.Value(vector[0]), self._edb.Utility.Value(vector[1])
            )
            polygon_data = self._edb.Geometry.PolygonData.CreateFromArcs(
                self.polygon_data.edb_api.GetArcData(), True
            )
            polygon_data.Move(_vector)
            return self.api_object.SetPolygonData(polygon_data)
```

2024-01-25 10:43 UTC, SMoraisAnsys commented on pyaedt/edb_core/edb_data/primitives_data.py
> +                        return self.api_object.SetPolygonData(polygon_data)
```suggestion
            elif isinstance(center, list) and len(center) == 2:
                center = self._edb.Geometry.PointData(
                    self._edb.Utility.Value(center[0]), self._edb.Utility.Value(center[1])
                )
                polygon_data.Scale(factor, center)
                return self.api_object.SetPolygonData(polygon_data)
```

2024-01-25 10:43 UTC, SMoraisAnsys commented on pyaedt/edb_core/edb_data/primitives_data.py
> +            else:
```suggestion
            elif isinstance(center, list) and len(center) == 2:
```

2024-01-25 10:43 UTC, SMoraisAnsys commented on pyaedt/edb_core/edb_data/primitives_data.py
> +                    return True
```suggestion
        if layer and isinstance(layer, str) and layer in self._pedb.stackup.signal_layers:
            polygon_data = self._edb.Geometry.PolygonData.CreateFromArcs(
                self.polygon_data.edb_api.GetArcData(), True
            )
            moved_polygon = self._pedb.modeler.create_polygon(
                main_shape=polygon_data, net_name=self.net_name, layer_name=layer
            )
            if moved_polygon:
                self.delete()
                return True
```

2024-01-25 10:47 UTC, SMoraisAnsys commented on pyaedt/edb_core/edb_data/primitives_data.py
> +            else:
Btw, this is to be consistent with other methods way of working

2024-01-25 16:53 UTC, SMoraisAnsys approved these changes

2024-01-25 16:53 UTC, merged