Remove any usage of bare exception.
ansys/pyaedt pull request #4331
Opened 2024-03-07 10:50 UTC by MaxJPRey

It's generally considered good practice to use `except Exception as e`: rather than a bare `except:` because it avoids catching some exceptions that you typically don't want to catch, like keyboard interrupts and system exits. It also allows you to access and use the actual exception object, which can be helpful for debugging.

2024-03-07 13:36 UTC, SMoraisAnsys submitted a review, later dismissed

2024-03-08 11:55 UTC, MaxJPRey commented
> @MaxJPRey To avoid codacy failure, I would recommand to not use `except Exception as e:` but `except Exception:` since `e` is never used afterward.

@SMoraisAnsys I fully agree. I will do it.

2024-03-08 13:18 UTC, SMoraisAnsys commented
@MaxJPRey Since you are busy, feel free to let me do the changes. Just ping me so that I get notified 😄

2024-03-15 17:24 UTC, MaxJPRey commented
> @MaxJPRey Since you are busy, feel free to let me do the changes. Just ping me so that I get notified 😄

@SMoraisAnsys It is done.

2024-03-17 21:55 UTC, SMoraisAnsys requested changes
Found 2 `except Exception as e` left. Otherwise, all good for me :)
Thanks for the huge refactoring

2024-03-17 21:55 UTC, SMoraisAnsys commented on _unittest/test_01_Design.py
> +        except Exception as e:
```suggestion
        except Exception:
```

2024-03-17 21:55 UTC, SMoraisAnsys commented on _unittest/test_01_Design.py
> +        except Exception as e:
```suggestion
        except Exception:
```

2024-03-19 08:11 UTC, SMoraisAnsys submitted a review, later dismissed

2024-03-19 08:28 UTC, Samuelopez-ansys approved these changes

2024-03-22 11:27 UTC, Samuelopez-ansys approved these changes

2024-03-22 11:27 UTC, Samuelopez-ansys commented on pyaedt/aedt_logger.py
> +            except Exception:
```suggestion
            except Exception:  # pragma: no cover
```

2024-03-22 11:27 UTC, Samuelopez-ansys commented on pyaedt/aedt_logger.py
> +        except Exception:
```suggestion
        except Exception:  # pragma: no cover
```

2024-03-22 13:46 UTC, Samuelopez-ansys submitted a review, later dismissed

2024-03-22 14:41 UTC, Samuelopez-ansys commented
@MaxJPRey I cancelled the workflow before, because there are some unit test failing, apart from Codacy that is complaining. I will debug next week and try to find the issue.

2024-03-26 10:11 UTC, SMoraisAnsys approved these changes
LGTM

2024-03-26 17:27 UTC, merged