fixed region definition for RZ designs
ansys/pyaedt pull request #4360
Opened 2024-03-13 12:54 UTC by IreneWoyna

2024-03-13 17:23 UTC, MaxJPRey commented on pyaedt/modeler/cad/Primitives2D.py
> +            If a list of floats or str, interpret as adding for ``["+X", "+Y", "-X", "-Y"]`` for XY geometry mode,
```suggestion
            If a list of floats or str, interpret as adding ``["+X", "+Y", "-X", "-Y"]`` for XY geometry mode,
```

2024-03-14 10:39 UTC, SMoraisAnsys requested changes

2024-03-14 10:39 UTC, SMoraisAnsys commented on pyaedt/modeler/cad/Primitives2D.py
>          if not isinstance(pad_percent, list):
```suggestion
        """
        SOLUTION_TYPES = ["TransientXY", "MagnetostaticXY", "EddyCurrentXY", "ElectrostaticXY", "DCConductionXY", "ACConductionXY"]
        if not isinstance(pad_percent, list):
```

2024-03-14 10:39 UTC, SMoraisAnsys commented on pyaedt/modeler/cad/Primitives2D.py
> +                ]:
```suggestion
                if self._app.solution_type in SOLUTION_TYPES:
```

2024-03-14 10:39 UTC, SMoraisAnsys commented on pyaedt/modeler/cad/Primitives2D.py
> +                ]:
```suggestion
                if self._app.solution_type in SOLUTION_TYPES:
```

2024-03-14 10:40 UTC, SMoraisAnsys commented on pyaedt/modeler/cad/Primitives2D.py
> +                ]:
@IreneWoyna Some minor changes to ease maintenance

2024-03-14 15:56 UTC, Samuelopez-ansys commented
@SMoraisAnsys I think the suggestions are already merged.

2024-03-14 16:14 UTC, PipKat commented on pyaedt/modeler/cad/Primitives2D.py
> +            If a list of floats or str, interpret as adding ``["+X", "+Y", "-X", "-Y"]`` for XY geometry mode,
```suggestion
            If a list of floats or strings, interpret as adding ``["+X", "+Y", "-X", "-Y"]`` for XY geometry mode,
```
Avoid abbreviations in descriptions.

2024-03-14 16:15 UTC, PipKat commented on pyaedt/modeler/cad/Primitives2D.py
>              Region definition in percentage or absolute value. The default is `True``.
```suggestion
            Whether the region definition is a percentage or absolute value. The default is `True``.
```
Does "True" mean one or the other? If so, "The default is ``True``, in which case the region definition is a X."

2024-03-14 17:36 UTC, SMoraisAnsys approved these changes

2024-03-15 09:06 UTC, gmalinve commented on _unittest/test_09_Primitives2D.py
> +        assert self.axisymmetrical.modeler.create_region([100, 50, 20])
@IreneWoyna I'd assert after each create_region that your Region object is now in the list of the objects. Before the delete()

2024-03-21 08:01 UTC, gmalinve approved these changes

2024-03-21 08:01 UTC, merged