FIX: Defining Modelithics attributes change
ansys/pyaedt pull request #5233
Opened 2024-10-02 11:36 UTC by ramin4667

This PR updates the lumped export uni tests to pass the Modelithics attributes by changing the part library to Modelithics.

2024-10-03 03:24 UTC, myoung301 requested changes
Can we test for the new error message somewhere? The message that gets issued when the part library is not set to Modelithics?

2024-10-03 17:03 UTC, ramin4667 commented
> Can we test for the new error message somewhere? The message that gets issued when the part library is not set to Modelithics?

Unit tests are updated.

2024-10-04 15:41 UTC, SMoraisAnsys approved these changes
LGTM
@myoung301 I think the changes follow your request right ?

2024-10-04 16:05 UTC, myoung301 approved these changes

2024-10-04 16:06 UTC, merged