FEAT: method to add notes on design
ansys/pyaedt pull request #5271
Opened 2024-10-09 15:15 UTC by anur7

2024-10-10 06:38 UTC, SMoraisAnsys submitted a review, later dismissed
LGTM, I left a minor comment.

2024-10-10 06:38 UTC, SMoraisAnsys commented on src/ansys/aedt/core/application/design.py
> +            self.logger.error("Text is not valid.")
```suggestion
            self.logger.error("Input type of edit_notes is not valid.")
```

2024-10-10 06:55 UTC, gmalinve requested changes

2024-10-11 12:52 UTC, gmalinve approved these changes
LGTM.

2024-10-11 13:01 UTC, merged