Refactor: Improve compute power
ansys/pyaedt pull request #5514
Opened 2024-12-02 10:05 UTC by hui-zhou-a

## Description
**Please provide a brief description of the changes made in this pull request.**

## Issue linked
**Please mention the issue number or describe the problem this pull request addresses.**

## Checklist
- [ ] I have tested my changes locally.
- [ ] I have added necessary documentation or updated existing documentation.
- [ ] I have followed the coding style guidelines of this project.
- [ ] I have added appropriate tests (unit, integration, system).
- [ ] I have reviewed my changes before submitting this pull request.
- [ ] I have linked the issue or issues that are solved by the PR if any.
- [ ] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

2024-12-05 08:45 UTC, hui-zhou-a commented
@Samuelopez-ansys @maxcapodi78 please help to review and merge this PR.

2024-12-09 16:53 UTC, maxcapodi78 requested changes
Few suggestions and comments

2024-12-09 16:53 UTC, maxcapodi78 commented on src/ansys/aedt/core/application/analysis_3d_layout.py
> +        :class:`ansys.aedt.core.visualization.post.post_processor`
why did you change the return class with a module?

2024-12-09 16:53 UTC, maxcapodi78 commented on src/ansys/aedt/core/visualization/post/post_3dlayout.py
> +    def compute_power_by_layer(self, solution=None):
I would have the possibility to filter by layer or net in any case (even if now is much faster). On big board could simplify the post-processing

2024-12-09 16:53 UTC, maxcapodi78 commented on src/ansys/aedt/core/visualization/post/post_3dlayout.py
> +    def compute_power_by_net(self, solution=None):
Same as above. I would also leave the filter solution (with None as default) to be able to compute for the entire board or only for the selected layers/nets

2024-12-10 15:10 UTC, maxcapodi78 approved these changes
LGTM

2024-12-10 15:23 UTC, merged