CHORE: refacto maxwell test
ansys/pyaedt pull request #5601
Opened 2024-12-20 14:03 UTC by gmalinve

## Description
**Please provide a brief description of the changes made in this pull request.**

## Issue linked
**Please mention the issue number or describe the problem this pull request addresses.**

## Checklist
- [ ] I have tested my changes locally.
- [ ] I have added necessary documentation or updated existing documentation.
- [ ] I have followed the coding style guidelines of this project.
- [ ] I have added appropriate tests (unit, integration, system).
- [ ] I have reviewed my changes before submitting this pull request.
- [ ] I have linked the issue or issues that are solved by the PR if any.
- [ ] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

2025-01-07 09:43 UTC, SMoraisAnsys reviewed
Thanks for this huge refactoring @gmalinve 
I left some minor comments, note that the ones of `Eddy current` -> `Eddy Current` can probably be discarded (but check the removal of an unnecessary `" "`)

On top of those comments here are three things I want to bring up:
- In future refactoring / test addition (or even here if you want) could you try to make the tests follow the pattern : Setup, Calls, Asserts (and TearDown if required) ? This would help to understand what is tested. Note that this will also lead to split some test into more tests (but the code is already here so that isn't really an issue)
- Would it make sense add extra fixture to also embed `m3d_app.solution_type = SOLUTIONS.WHATEVER` ? I see that multiple tests start with such definition and I was wondering if it would make sense.
- Could you try running the tests locally and use random testing ? For example, add 
```
import pytest
import random

def pytest_collection_modifyitems(session, config, items):
    random.shuffle(items)
```
in the test file or you can have a look at https://pypi.org/project/pytest-randomly/

2025-01-07 12:45 UTC, gmalinve commented on src/ansys/aedt/core/maxwell.py
> +                return False
@SMoraisAnsys this return statement was wrong. 
If the boundary creation fails this must not return True but False.

2025-01-09 08:24 UTC, SMoraisAnsys requested changes
On top of the previous changes comments, here are some new ones ^^

2025-01-09 08:24 UTC, SMoraisAnsys commented on src/ansys/aedt/core/maxwell.py
> +        return False
```suggestion
            self.logger.info(f"Boundary {name} has been correctly created.")
            self._boundaries[bound.name] = bound
            return bound
        self.logger.error(f"Boundary {name} was not created.")
        return False
```
In the previous method to create boundary, logging was performed. We should also have it here.

2025-01-09 08:24 UTC, SMoraisAnsys commented on src/ansys/aedt/core/maxwell.py
> +            return False
```suggestion
        list_coordinates = [
            u_vector_origin_coordinates_master,
            u_vector_origin_coordinates_slave,
            u_vector_pos_coordinates_master,
            u_vector_pos_coordinates_slave,
        ]
        if any(not isinstance(coordinates, list) for coordinates in list_coordinates):
            self.logger.error("Please provide a list of coordinates for U vectors.")
            return False
        for coordinates in list_coordinates:
            if any(not isinstance(x, str) for x in coordinates):
                self.logger.error("Elements of coordinates system must be strings in the form of ``value+unit``.")
                return False
        if any(len(coordinates) != 3 for coordinates in list_coordinates):
            self.logger.error("Vector must contain 3 elements for x, y, and z coordinates.")
            return False
```

2025-01-09 08:26 UTC, SMoraisAnsys commented
@gmalinve Thanks again for this huge refactoring and bug fixes. I don't think I'll have other changes to propose so once my requests are handled, it should be ready to be merged :)

2025-01-09 08:30 UTC, gmalinve commented on src/ansys/aedt/core/modules/mesh.py
> -        assignment = self._app.modeler.convert_to_selections(assignment, True)
@SMoraisAnsys because it's done as the very first line of this method. I was repetitive.

2025-01-09 08:31 UTC, gmalinve commented on src/ansys/aedt/core/modules/mesh.py
> -        assignment = self._app.modeler.convert_to_selections(assignment, True)
@SMoraisAnsys same comment as before, it's done as a first line of code.

2025-01-10 11:25 UTC, SMoraisAnsys submitted a review, later dismissed

2025-01-13 10:58 UTC, SMoraisAnsys approved these changes
LGTM

2025-01-13 11:00 UTC, merged