DOCS: Add the changelog.
ansys/pyaedt pull request #5612
Opened 2024-12-27 10:52 UTC by MaxJPRey

2024-12-27 17:34 UTC, SMoraisAnsys commented
Thanks for bringing this tipic @MaxJPRey 
It is part of the changes that should be performed before reaching v1.0
We were planning to use it in january, thanks for the PR haha Please do not merge it until I show some things to @Samuelopez-ansys :)

2024-12-27 17:35 UTC, SMoraisAnsys requested changes
Adding this review until I explain a few things to the pyaedt mainteneurs

2024-12-30 08:54 UTC, MaxJPRey commented
> Adding this review until I explain a few things to the pyaedt mainteneurs

No problem @SMoraisAnsys . It can definitely wait. I was mainly testing something while creating this PR.

2025-02-25 07:03 UTC, Samuelopez-ansys commented
@SMoraisAnsys I think we can go ahead with this PR :)

2025-02-26 12:58 UTC, SMoraisAnsys requested changes
On top of the requested changes, I'll have to give access to the repo to our bot.
Let me try to do that today :)

2025-02-26 12:58 UTC, SMoraisAnsys commented on pyproject.toml
> +package = "ansys.<product>.<library>"
```suggestion
package = "ansys.aedt.core"
```

2025-02-26 12:58 UTC, SMoraisAnsys commented on pyproject.toml
> +filename = "CHANGELOG.md"
We need to add this file in the PR

2025-02-28 19:38 UTC, MaxJPRey commented
Thanks @SMoraisAnsys for adding the missing file.

2025-03-07 10:58 UTC, Samuelopez-ansys approved these changes

2025-03-07 11:08 UTC, merged