FIX: Remove access to member before their definition.
ansys/pyaedt pull request #5622
Opened 2024-12-31 18:06 UTC by MaxJPRey

2024-12-31 18:10 UTC, MaxJPRey commented on tests/system/general/test_45_FilterSolutions/test_filter/test_attributes.py
> +    def test_minimum_order_stop_band_freq_second_time(self):
@ramin4667 I just renamed the test. In this file it is defined twice if you look few lines above.
I was not sure if it was done on purpose to maybe set up again some parameters.

2025-01-02 09:00 UTC, SMoraisAnsys approved these changes
LGTM

2025-01-02 13:13 UTC, SMoraisAnsys requested changes
Previous review was performed on my cell phone and I missed the test duplication (though it was only test names)
I think that one of the test should be removed since they are duplicates.

2025-01-02 13:57 UTC, ramin4667 commented on tests/system/general/test_45_FilterSolutions/test_filter/test_attributes.py
> +    def test_minimum_order_stop_band_freq_second_time(self):
@MaxJPRey The duplicated test is removed.

2025-01-02 17:13 UTC, MaxJPRey commented on tests/system/general/test_45_FilterSolutions/test_filter/test_attributes.py
> +    def test_minimum_order_stop_band_freq_second_time(self):
Thanks @ramin4667 .

2025-01-02 17:15 UTC, MaxJPRey commented
> Previous review was performed on my cell phone and I missed the test duplication (though it was only test names) I think that one of the test should be removed since they are duplicates.

It is done @SMoraisAnsys .

2025-01-03 10:10 UTC, SMoraisAnsys approved these changes

2025-01-03 14:15 UTC, merged